name: Build Static ARM64 FastIO for Lua 5.3

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-static-arm64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU for ARM64
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create Static Lua 5.3 Dockerfile
      run: |
        cat > Dockerfile.static << 'EOF'
        FROM arm64v8/ubuntu:22.04
        
        # Install build dependencies
        RUN apt-get update && apt-get install -y \
            build-essential \
            lua5.3-dev \
            liblua5.3-dev \
            pkg-config \
            file \
            wget \
            && rm -rf /var/lib/apt/lists/*
        
        WORKDIR /build
        COPY fastio_read_only.c .
        
        # Build statically linked version - no external Lua dependencies
        RUN gcc -O3 -fPIC -Wall -Wextra -std=c99 \
            -DLUA_COMPAT_5_3 -DLUA_USE_LINUX \
            -march=armv8-a -mtune=cortex-a72 \
            -DNDEBUG -fstack-protector-strong \
            -D_FORTIFY_SOURCE=2 -fvisibility=hidden \
            -I/usr/include/lua5.3 \
            -c fastio_read_only.c -o fastio.o
        
        # Create shared library without Lua dependencies
        RUN gcc -shared -fPIC \
            -Wl,-soname,fastio.so \
            -Wl,--as-needed -Wl,-z,relro,-z,now \
            -Wl,--strip-all \
            -o fastio.so fastio.o -lm -ldl
        
        # Verify no Lua dependencies
        RUN echo "=== Build Info ===" && \
            file fastio.so && \
            ls -la fastio.so && \
            echo "=== Dependencies ===" && \
            ldd fastio.so || echo "Static dependencies only"
        
        # Create version that works with embedded Lua
        RUN cp fastio.so fastio_static.so
        
        CMD ["tail", "-f", "/dev/null"]
        EOF
    
    - name: Build Static ARM64 FastIO
      run: |
        echo "Building static ARM64 FastIO for Lua 5.3..."
        
        docker buildx build --platform linux/arm64 \
          -f Dockerfile.static \
          -t lua53-static-arm64:latest \
          --load \
          .
        
        mkdir -p output
        
        # Extract both versions
        docker run --rm --platform linux/arm64 \
          -v $PWD/output:/output \
          lua53-static-arm64:latest \
          sh -c "cp /build/fastio.so /output/ && cp /build/fastio_static.so /output/"
        
        echo "=== Build Results ==="
        ls -la output/
        echo "=== File Types ==="
        file output/*.so
    
    - name: Upload Static ARM64 binary
      uses: actions/upload-artifact@v4
      with:
        name: fastio-lua53-static-arm64
        path: output/*.so
        retention-days: 90
