name: Build LoadLib ARM64 FastIO (package.loadlib compatible)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-loadlib-arm64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU for ARM64
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create LoadLib Build Dockerfile
      run: |
        cat > Dockerfile.loadlib << 'EOF'
        FROM arm64v8/alpine:3.18
        
        RUN apk add --no-cache build-base musl-dev file
        
        WORKDIR /build
        COPY fastio_loadlib.c .
        
        # Build for package.loadlib compatibility
        RUN gcc -O3 -fPIC -Wall -Wextra -std=c99 \
            -march=armv8-a -mtune=cortex-a72 \
            -DNDEBUG -fstack-protector \
            -c fastio_loadlib.c -o fastio.o
        
        RUN gcc -shared -fPIC \
            -Wl,-soname,fastio.so \
            -o fastio.so fastio.o
        
        # Verify build and symbols
        RUN echo "=== LoadLib ARM64 FastIO ===" && \
            file fastio.so && \
            ls -la fastio.so && \
            echo "=== Exported Symbols ===" && \
            nm -D fastio.so | grep fastio || echo "Symbols may be stripped"
        
        CMD ["tail", "-f", "/dev/null"]
        EOF
    
    - name: Build LoadLib ARM64 FastIO
      run: |
        docker buildx build --platform linux/arm64 \
          -f Dockerfile.loadlib \
          -t fastio-loadlib-arm64:latest \
          --load \
          .
        
        mkdir -p output
        
        docker run --rm --platform linux/arm64 \
          -v $PWD/output:/output \
          fastio-loadlib-arm64:latest \
          cp /build/fastio.so /output/
        
        echo "=== LoadLib Build Results ==="
        ls -la output/
        file output/fastio.so
    
    - name: Upload LoadLib ARM64 binary
      uses: actions/upload-artifact@v4
      with:
        name: fastio-loadlib-arm64
        path: output/fastio.so
        retention-days: 90
