name: Build LuaJ ARM64 FastIO (System.load compatible)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-luaj-arm64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU for ARM64
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create LuaJ Build Dockerfile
      run: |
        cat > Dockerfile.luaj << 'EOF'
        FROM arm64v8/alpine:3.18
        
        RUN apk add --no-cache build-base musl-dev file
        
        WORKDIR /build
        COPY fastio_luaj.c .
        
        # Build for LuaJ/System.load compatibility
        RUN gcc -O3 -fPIC -Wall -Wextra -std=c99 \
            -march=armv8-a -mtune=cortex-a72 \
            -DNDEBUG -fstack-protector \
            -c fastio_luaj.c -o fastio.o
        
        # Create shared library with proper exports
        RUN gcc -shared -fPIC \
            -Wl,-soname,fastio.so \
            -Wl,--export-dynamic \
            -o fastio.so fastio.o
        
        # Verify build and check exports
        RUN echo "=== LuaJ ARM64 FastIO ===" && \
            file fastio.so && \
            ls -la fastio.so && \
            echo "=== Function Exports ===" && \
            nm -D fastio.so | grep -E "(fastio|luaopen)" || echo "Checking for symbols..."
        
        CMD ["tail", "-f", "/dev/null"]
        EOF
    
    - name: Build LuaJ ARM64 FastIO
      run: |
        docker buildx build --platform linux/arm64 \
          -f Dockerfile.luaj \
          -t fastio-luaj-arm64:latest \
          --load \
          .
        
        mkdir -p output
        
        docker run --rm --platform linux/arm64 \
          -v $PWD/output:/output \
          fastio-luaj-arm64:latest \
          cp /build/fastio.so /output/
        
        echo "=== LuaJ Build Results ==="
        ls -la output/
        file output/fastio.so
    
    - name: Upload LuaJ ARM64 binary
      uses: actions/upload-artifact@v4
      with:
        name: fastio-luaj-arm64
        path: output/fastio.so
        retention-days: 90
